Normalization [Min Max Scaler] --> 0 to 1

Age 24,25,26,27,28,30

Transformation --> xscaled = (x - xmin) / (xmax - xmin)

(24 - 24 )/(30 - 24)

Mostly use standardization in Machine learning and normalization in deep learning.

In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset('taxis')
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [3]:
from sklearn.preprocessing import MinMaxScaler # importing MinMaxScaler from sklearn.preprocessing

In [4]:
min_max = MinMaxScaler()

In [5]:
min_max

MinMaxScaler()

In [6]:
df[['distance', 'fare', 'tip', 'total']]

      distance  fare   tip  total
0         1.60   7.0  2.15  12.95
1         0.79   5.0  0.00   9.30
2         1.37   7.5  2.36  14.16
3         7.70  27.0  6.15  36.95
4         2.16   9.0  1.10  13.40
...        ...   ...   ...    ...
6428      0.75   4.5  1.06   6.36
6429     18.74  58.0  0.00  58.80
6430      4.14  16.0  0.00  17.30
6431      1.12   6.0  0.00   6.80
6432      3.85  15.0  3.36  20.16

[6433 rows x 4 columns]

In [7]:
max(df['distance']), min(df['distance']), max(df['fare']), min(df['fare']), max(df['tip']), min(df['tip']), max(df['total']), min(df['total']) # checking the max and min values of the columns

(36.7, 0.0, 150.0, 1.0, 33.2, 0.0, 174.82, 1.3)

In [8]:
max(df['total']), min(df['total'])

(174.82, 1.3)

In [9]:
min_max.fit(df[['distance', 'fare', 'tip', 'total']]) # fitting the data to the MinMaxScaler

MinMaxScaler()

In [10]:
min_max.transform(df[['distance', 'fare', 'tip', 'total']]) # transforming the data to the MinMaxScaler

array([[0.04359673, 0.04026846, 0.06475904, 0.06713923],
       [0.02152589, 0.02684564, 0.        , 0.0461042 ],
       [0.0373297 , 0.04362416, 0.07108434, 0.07411249],
       ...,
       [0.11280654, 0.10067114, 0.        , 0.09220839],
       [0.03051771, 0.03355705, 0.        , 0.03169663],
       [0.10490463, 0.09395973, 0.10120482, 0.10869064]], shape=(6433, 4))

In [11]:
min_max.fit_transform(df[['distance', 'fare', 'tip', 'total']]) # fitting and transforming the data to the MinMaxScaler

array([[0.04359673, 0.04026846, 0.06475904, 0.06713923],
       [0.02152589, 0.02684564, 0.        , 0.0461042 ],
       [0.0373297 , 0.04362416, 0.07108434, 0.07411249],
       ...,
       [0.11280654, 0.10067114, 0.        , 0.09220839],
       [0.03051771, 0.03355705, 0.        , 0.03169663],
       [0.10490463, 0.09395973, 0.10120482, 0.10869064]], shape=(6433, 4))

In [12]:
import pandas as pd
df2 = pd.DataFrame(min_max.fit_transform(df[['distance', 'fare', 'tip', 'total']]), columns=['distance', 'fare', 'tip', 'total']) # creating a new dataframe with the transformed data

In [13]:
df2.sample(10)

      distance      fare       tip     total
3582  0.019074  0.043624  0.064759  0.067139
6143  0.039510  0.050336  0.000000  0.046104
2898  0.277929  0.281879  0.000000  0.259336
5698  0.038692  0.040268  0.058735  0.048698
3889  0.000000  0.010067  0.000000  0.011526
2944  0.117166  0.117450  0.137048  0.150127
5978  0.134877  0.125570  0.000000  0.108979
298   0.232970  0.167785  0.211145  0.234959
1339  0.024251  0.030201  0.000000  0.046104
2964  0.261580  0.234899  0.000000  0.204587

In [14]:
df2.head()

   distance      fare       tip     total
0  0.043597  0.040268  0.064759  0.067139
1  0.021526  0.026846  0.000000  0.046104
2  0.037330  0.043624  0.071084  0.074112
3  0.209809  0.174497  0.185241  0.205452
4  0.058856  0.053691  0.033133  0.069733

In [15]:
max(df['distance']), min(df['distance']), max(df['fare']), min(df['fare']), max(df['tip']), min(df['tip']) # checking the max and min values of the columns

(36.7, 0.0, 150.0, 1.0, 33.2, 0.0)

In [16]:
# checking the max and min values of the columns
max(df2['distance']), min(df2['distance']), max(df2['fare']), min(df2['fare']), max(df2['tip']), min(df2['tip']) # checking the max and min values of the columns

(1.0, 0.0, 0.9999999999999999, 0.0, 1.0, 0.0)

In [17]:
max(df['total']), min(df['total']) , max(df2['total']), min(df2['total']) # checking the max and min values of the columns

(174.82, 1.3, 1.0, 0.0)